/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication1;

import javax.swing.JFileChooser;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.CardLayout;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author moataz
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home(String email,String Fname,String Lname,String Answer,String jComboBox1,String jComboBox2,String buttonGroup1,String jDateChooser1) {
        initComponents();
        UserNamePrintFiled.setText(Fname+" "+Lname);
        this.EmailPrintFiled.setText(email);
        this.AnswerPrintFiled2.setText(Answer);
        this.GenderPrintFiled.setText(buttonGroup1);
        this.CountryFiled.setText(jComboBox1);
        this.QuestionPrintFiled.setText(jComboBox2);
        this.BDPrintFiled.setText(jDateChooser1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserNamePrintFiled = new javax.swing.JLabel();
        EmailPrintFiled = new javax.swing.JLabel();
        GenderPrint = new javax.swing.JLabel();
        GenderPrintFiled = new javax.swing.JLabel();
        GenderPrint1 = new javax.swing.JLabel();
        BDPrintFiled = new javax.swing.JLabel();
        GenderPrint2 = new javax.swing.JLabel();
        QuestionPrintFiled = new javax.swing.JLabel();
        GenderPrint3 = new javax.swing.JLabel();
        AnswerPrintFiled2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        GenderPrint4 = new javax.swing.JLabel();
        CountryFiled = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Home");
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(300, 400));
        jLabel1.setName(""); // NOI18N

        Username.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("User Name");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        UserNamePrintFiled.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        UserNamePrintFiled.setForeground(new java.awt.Color(255, 255, 255));
        UserNamePrintFiled.setText("1");

        EmailPrintFiled.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        EmailPrintFiled.setForeground(new java.awt.Color(255, 255, 255));
        EmailPrintFiled.setText("1");

        GenderPrint.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        GenderPrint.setForeground(new java.awt.Color(255, 255, 255));
        GenderPrint.setText("Gender");

        GenderPrintFiled.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        GenderPrintFiled.setForeground(new java.awt.Color(255, 255, 255));
        GenderPrintFiled.setText("1");

        GenderPrint1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        GenderPrint1.setForeground(new java.awt.Color(255, 255, 255));
        GenderPrint1.setText("Birth Day");

        BDPrintFiled.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BDPrintFiled.setForeground(new java.awt.Color(255, 255, 255));
        BDPrintFiled.setText("1");

        GenderPrint2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        GenderPrint2.setForeground(new java.awt.Color(255, 255, 255));
        GenderPrint2.setText("Question");

        QuestionPrintFiled.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        QuestionPrintFiled.setForeground(new java.awt.Color(255, 255, 255));
        QuestionPrintFiled.setText("1");

        GenderPrint3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        GenderPrint3.setForeground(new java.awt.Color(255, 255, 255));
        GenderPrint3.setText(" Answer");

        AnswerPrintFiled2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        AnswerPrintFiled2.setForeground(new java.awt.Color(255, 255, 255));
        AnswerPrintFiled2.setText("1");

        jButton1.setForeground(new java.awt.Color(59, 89, 152));
        jButton1.setText("PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GenderPrint4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        GenderPrint4.setForeground(new java.awt.Color(255, 255, 255));
        GenderPrint4.setText("Country");

        CountryFiled.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CountryFiled.setForeground(new java.awt.Color(255, 255, 255));
        CountryFiled.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNamePrintFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailPrintFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(GenderPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GenderPrintFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GenderPrint3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderPrint4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderPrint1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderPrint2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuestionPrintFiled, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BDPrintFiled, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnswerPrintFiled2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CountryFiled, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username)
                    .addComponent(UserNamePrintFiled))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailPrintFiled)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GenderPrint)
                    .addComponent(GenderPrintFiled))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(GenderPrint4)
                        .addGap(18, 18, 18)
                        .addComponent(GenderPrint1)
                        .addGap(18, 18, 18)
                        .addComponent(GenderPrint2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CountryFiled)
                        .addGap(18, 18, 18)
                        .addComponent(BDPrintFiled)
                        .addGap(18, 18, 18)
                        .addComponent(QuestionPrintFiled)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderPrint3)
                    .addComponent(AnswerPrintFiled2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path = "";
        JFileChooser pdf = new JFileChooser();
        pdf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = pdf.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION){
            path = pdf.getSelectedFile().getPath();
        }
        Document doc = new Document();
        try {
            
            PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream(path  +"\\Data.pdf"));
            doc.open();
            Paragraph Name = new Paragraph("Name : "+UserNamePrintFiled.getText());
            Paragraph Email = new Paragraph("Email : "+EmailPrintFiled.getText());
            Paragraph Gender = new Paragraph("Gender : "+GenderPrintFiled.getText());
            Paragraph Country = new Paragraph("Country : "+CountryFiled.getText());
            Paragraph Birthday = new Paragraph("Birthday : "+BDPrintFiled.getText());
            Paragraph Question = new Paragraph("Question : "+QuestionPrintFiled.getText());
            Paragraph Answer = new Paragraph("Answer : "+AnswerPrintFiled2.getText());
            
            
            doc.add(Name);
            doc.add(Email);
            doc.add(Gender);
            doc.add(Country);
            doc.add(Birthday);
            doc.add(Question);
            doc.add(Answer);
            
            doc.close();
            System.out.println("Done Saved");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnswerPrintFiled2;
    private javax.swing.JLabel BDPrintFiled;
    private javax.swing.JLabel CountryFiled;
    private javax.swing.JLabel EmailPrintFiled;
    private javax.swing.JLabel GenderPrint;
    private javax.swing.JLabel GenderPrint1;
    private javax.swing.JLabel GenderPrint2;
    private javax.swing.JLabel GenderPrint3;
    private javax.swing.JLabel GenderPrint4;
    private javax.swing.JLabel GenderPrintFiled;
    private javax.swing.JLabel QuestionPrintFiled;
    private javax.swing.JLabel UserNamePrintFiled;
    private javax.swing.JLabel Username;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
